mysociety/caps

caps/models.py
caps/tests/test_models.py
caps/views.py
templates/home.html

Add function for percentage of councils with a plan

---

caps/management/commands/preprocess.py

Just show an error message and continue. Fixes #25

Handle a plan that can't be downloaded without erroring

---

.github/workflows/django.yml
Vagrantfile
conf/dev_packages
conf/packages
manage.py
script/bootstrap
script/console
script/makemigrations
script/manage
script/migrate
script/server
script/test
script/update

This does the following:
* Updates the Vagrant box to a minimal-install of Debian Buster
* Cleans up the various package files a bit
* Removes some superfluous arguments and commands from the Vagrantfile
* Removes the virtualenv
This last may seem a little odd, but we're planning on running this in containers in production which will take the place of the virtualenv in terms of environment isolation; this is a step towards that.

Infra improvements

---

script/update

Done in order to prevent it prompting for confirmation

Use the `--noinput` flag for rebuild_index

---

caps/static/scss/alpha-banner.scss
caps/static/scss/main.scss
caps/templates/about.html
caps/templates/base.html
caps/templates/includes/alpha-banner.html
caps/templates/includes/site-subheader.html
caps/urls.py
caps/views.py

Alpha banner

---

caps/mapit.py
caps/static/js/main.js
caps/static/scss/main.scss
caps/templates/base.html
caps/templates/home.html
caps/templates/includes/location-search-form.html
caps/templates/location_results.html
caps/templates/postcode_results.html
caps/tests/test_mapit.py
caps/tests/test_views.py
caps/urls.py
caps/views.py
proj/settings.py

Couldn’t resist.
Fixes #41.
While I was there, I also DRYed up the location search form, so that the same partial is now shared between the homepage and council disambiguation page.

"Locate me automatically" link, as alternative to postcode search

---

.dockerignore
.gitignore
Dockerfile
README.md
Vagrantfile
conf/config.py.docker
conf/nginx.conf
development.yml
docker-compose.yml
production.yml
proj/settings.py
requirements.txt
script/bootstrap
script/build
script/server

This adds support for using Docker in production. Deploys once this is merged, we can made a few subsequent changes to use docker in development as well as ensuring that the master branch gets automatically deployed.

Docker integration

---

caps/api/routers.py
caps/api/serializers.py
caps/api/views.py
caps/templates/about.html
caps/tests/test_api.py
caps/urls.py
proj/settings.py
requirements.txt
templates/rest_framework/api.html
templates/rest_framework/base.html

Uses the Django REST framework to add a basic endpoint for council data
fixes #101

basic read only council api endpoint

---

caps/management/commands/import_plans.py
caps/tests/test_import.py
script/trial_update

Slightly better output when deleting a council, plus a script to make it easier to get a list of upcoming DB changes.

data update tweaks

---

caps/management/commands/add_council_websites.py
caps/management/commands/import_plans.py

either by updating the alternative names or in the case of NI just hard
coding them

fix missing council urls

---

.github/workflows/django.yml

Update github action to latest python version

---

.devcontainer/devcontainer.json
.vscode/launch.json
.vscode/settings.json
Dockerfile.dev
docker-compose.dev.yml
script/setup-in-docker

Makes a change to caps to allow the webserver to start without a fatal error if database hasn't been intialised (problem if docker image is loaded before the setup script has been run). 
Adds variant of the dockerfile with some additional packages needed for developing inside it. 
More generally, adds configuration files for vscode to reference dockerfile, and run a debug django server.

Config files for vscode/docker development

---

LICENSE.txt

Fixes #111.
Copied straight from https://github.com/mysociety/noiseworks.
@struan do you think we should update the year (2010!?) and/or change UKCOD to mySociety?

Add mySociety license file

---

.devcontainer/devcontainer.json
.vscode/settings.json
Dockerfile.dev
README.md
caps/management/commands/add_council_websites.py
caps/management/commands/fetch_and_process_promises.py
docker-compose.dev.yml
script/quick-setup
script/setup-in-docker

Generally this just changes the vscode config files, but there are two changes to the caps setup process in the latest commits.
These fix a future deprication warning for pandas, and add an explicit user agent for wikidata. This is technically [required anyway](https://meta.wikimedia.org/wiki/User-Agent_policy) but we've been getting away with it given our low traffic IPs.

Adjust config for codespaces

---

caps/models.py
scoring/static/scoring/img/chevron-white-left.svg
scoring/static/scoring/scss/background.scss
scoring/static/scoring/scss/buttons.scss
scoring/static/scoring/scss/typo.scss
scoring/templates/council_answers.html

Added hero section for council page

---

scoring/static/scoring/img/chevron-thin-black-down.svg
scoring/static/scoring/scss/buttons.scss
scoring/static/scoring/scss/label.scss
scoring/static/scoring/scss/main.scss
scoring/static/scoring/scss/question-page-about.scss
scoring/templates/question_answers.html

Also fixed hover effect for the about section in council page.
Fixes part of: #186 and #191

Added about section for question page

---

scoring/static/scoring/scss/scoring-table.scss
scoring/static/scoring/scss/table-question-council.scss
scoring/static/scoring/scss/table-section-council.scss
scoring/templates/council_answers.html
scoring/templates/scoring/home.html

-Fixed background-color in the single council tables
-Table-header in home page
-Margins on the single council page.

Minor fixes to styling

---

proj/hosts.py
proj/settings.py
requirements.txt
scoring/admin.py
scoring/apps.py
scoring/models.py
scoring/static/scss/scoring.scss
scoring/templates/scoring/base.html
scoring/templates/scoring/home.html
scoring/tests.py
scoring/urls.py
scoring/views.py

This is a minimal django app to check the scorecards host deployment works.

Scorecard test host

---

scoring/templates/scoring/home.html
scoring/templates/scoring/includes/score-bar.html

Generate homepage table bar charts via Django, rather than JavaScript

---

scoring/tests/test_views.py
scoring/views.py

Fix a few things with the display on the answer page.
This doesn't deal with the total in sub-sections.

Fix question display issues

---

caps/import_utils.py
caps/models.py
caps/templates/includes/council-powers.html

For importing the GLA: https://github.com/mysociety/caps/issues/251
This PR adds processing to list the correct powers of the GLA.

List correct powers of Greater London Authority

---

conf/config.py-example
conf/config.py.docker
docker-compose.dev.yml
docker-compose.yml
scoring/mixins.py
scoring/static/scoring/scss/down-message.scss
scoring/static/scoring/scss/login-form.scss
scoring/static/scoring/scss/main.scss
scoring/templates/scoring/down.html
scoring/templates/scoring/login.html
scoring/urls.py
scoring/views.py

Displays a down page is SCORECARDS_PRIVATE setting is true, and allows users to view site if logged in.
if you set SCORECARDS_PRIVATE in .env to True then restart docker that should require you to log in to see the site.
Fixes #235

Add down page and ability to password protect site

---

proj/settings.py

Just updating the scorecard version number, but doing a PR because so many things are in motion.

Increment dataset version

---

caps/management/commands/import_filter_data.py
scoring/templates/scoring/council.html
scoring/views.py

removed the budget as we don't have that data at the moment and then
moved political control down as it was smooshing up against the other
column where it was

display council data on council page

---

scoring/static/scoring/scss/about.scss
scoring/static/scoring/scss/main.scss
scoring/templates/scoring/about.html

I just added the "About page"
Fixes part of #192 
https://user-images.githubusercontent.com/13790153/150364697-bd56423d-367a-4fdc-aa61-097e5c6a776a.mov
Just my commits are the ones made today and from commit: c5ea7f60d5e23ba7b1480982084f839ae6b7af2a and the following ones.

Added "About us" page

---

scoring/static/scoring/js/main.js
scoring/static/scoring/scss/scoring-table.scss
scoring/templates/scoring/home.html

Sortable tables

---

scoring/models.py
scoring/tests/test_views.py

Quick PR to run tests, but changing the format to use '1.1.1' format rather than words.

Changed format of pretty question id

---

proj/settings.py
scoring/models.py

Three things:
1. Fixes a problem in the dataset where a deleted question was left in. 
2. Changes the pretty name for a few questions where they don't quite follow the rule. 
3. There is a third error in the live site where previously deleted questions are in from previous uploads. This will need to be cleaned out and reimported.

Tidy up deleted questions

---

scoring/templates/scoring/council.html

functionality incomplete so removing

remove links to individual question page

---

conf/nginx.conf

Untested. Copied from my traintimes config.
Part of https://github.com/mysociety/caps/issues/156

Add nginx gzip headers.

---

caps/management/commands/add_council_websites.py
caps/management/commands/import_emissions_data.py
caps/management/commands/import_plans.py
caps/templates/council_detail.html

Fixed #323. 
* Fixed bug in calculating per person and per area emissions for higher geographies.
* Improved wording on display of emissions data.
Needs to run `python manage.py import_emissions_data --all` after merge.

Fix combined emissions

---

caps/models.py
caps/templates/council_detail.html
caps/templates/includes/authority_type.html

correctly determine group type for northern ireland councils

---

scoring/templates/scoring/council.html
scoring/templates/scoring/includes/location-search-autocomplete.html
scoring/templates/scoring/includes/main-filter.html
scoring/templates/scoring/includes/scoring_url.html

Helps with search engine things
Fixes #330

always use homepage for links to single authority scoring list

---

scoring/models.py
scoring/static/scoring/js/main.js
scoring/static/scoring/scss/table-question-council.scss
scoring/templates/scoring/council.html
scoring/tests/test_views.py
scoring/views.py

Enables comparisons at a section and header question level.
Fixes #317

Add ability to compare councils to the council page

---

proj/settings.py

Please merge and update data on or after Thursday (02/03).

Update scorecard dataset to 1.2.0

---

caps/import_utils.py
caps/management/commands/preprocess.py

because this is how the plan import should work, so also fixes an issue
with plans not being updated

allow replace_csv_headers to output to a different file

---

caps/management/commands/fetch_scottish_reporting_data.py
caps/management/commands/process_scottish_reporting_data.py
proj/settings.py

This is an attempt to pull out some useful data from the mandatory scottish council climate reporting data.
To generate the data first create a `scottish` directory under data and then run:
`./manage.py fetch_scottish_reporting_data`
followed by
`./manage.py process_scottish_reporting_data`
this will download a load of excel files in the the `data\scottish` directory and then generate a number of CSV files in there with the parse out data.
if you run `process_scottish_reporting_data` you will see that you can limit the types processes which should speed things up a little if you don't want to process it all

Import scottish council climate reporting data

---

caps/templates/projects_list.html
caps/views.py

also remove some hidden code from the template that isn't required

add pagination to the council projects list

---

scoring/templates/scoring/includes/advanced-filter.html

Display badge on Scorecards homepage when filters are active

---

caps/static/caps/js/main.js
caps/static/caps/scss/feedback-modal.scss
caps/static/caps/scss/main.scss
caps/templates/about_data.html
caps/templates/home.html
caps/templates/includes/data-feedback-modal.html
caps/templates/includes/interstitial-modal.html
caps/urls.py
caps/views.py
conf/config.py.docker
docker-compose.dev.yml
docker-compose.yml

Adds a modal popup to download links asking for an email address to write to about how data is being used.
Fixes #346

data download feedback request popup 

---

caps/models.py
caps/templates/about_data.html
caps/templates/home.html
caps/tests/test_models.py
caps/tests/test_views.py
caps/views.py

341 only count plans as plans

---

caps/static/caps/scss/ceuk-card.scss
caps/templates/council_detail.html
caps/templates/style.html
caps/views.py

lets people easily search within the council's documents.
Fixes #219

add a search form on the council detail page

---

caps/management/commands/import_declarations.py
caps/management/commands/import_plans.py
caps/management/commands/import_promises.py
caps/models.py
caps/tests/test_models.py
caps/utils.py
scoring/management/commands/import_plan_scores.py

no need for them to be in PlanDocument given they are used for other
things so move them in to the utils module
Fixes #214

move csv conversion utils to utils

---

caps/models.py

correctly filter councils on has plan based on document type

---

caps/templates/caps/about.html

Will leave this PR open for a few days, in case there are any more changes incoming.

[CAPE] Minor change to CEUK wording on About page

---

caps/templates/caps/includes/survey-email.html

Mailchimp workflow tracks opens (booo), switch to an Alchemer based approach.
Addresses https://github.com/mysociety/climate-project/issues/30

Switch from mailchimp survey delay to Alchemer

---

caps/models.py

Addresses: https://github.com/mysociety/caps/issues/445
London is a SRA, but for filtering purposes, should be come up as a combined authority (otherwise not present on lists).

Combined authority drop down will include London.

---

scoring/templates/scoring/methodology2023.html
scoring/views.py

[Scorecards] Draft Methodology post-launch fixes

---

scoring/static/scoring/scss/buttons.scss
scoring/templates/scoring/home.html
scoring/templates/scoring/methodology2023.html
scoring/views.py

Hi @zarino 
Small PR with some changes:
-Copy change here:  Gov & Finance - question 4
-Added a download button for question spreadsheet on excel format.
Let me know if there is any feedback

[Scorecards] Methodology2023

---

scoring/templates/scoring/methodology2023.html
scoring/views.py

Hey @zarino 
Here is a draft for the PR, not sure if you want me to wait till next week.
List of changes
- Mandi Bissett (we are currently missing a ‘t’) and on same line volunteers (we need to remove the ‘s’)
- Leanne Wilson (Policy and Economic Advisor at North of Tyne Combined Authority)
Consultations - thank you’s
- Could we add Ecotricity to the list of thank you in our consultations.
Let me know if there is any feedback.

Methodology2023 Updated copy

---

scoring/templates/scoring/home.html
scoring/templates/scoring/methodology2023.html

Minor changes to the homepage and methodology draft copy in the volunteers section. 
This PR updates copy and link according to the changes requested by CEUK on the volunteer correction section:
https://docs.google.com/document/d/1PkvYxW7wKB9OjltoRfpt1NcqS0IffP3HL9RTJiMQbuU/edit

[Scorecards] Updated copy for volunteers applications

---

caps/management/commands/link_combined_authorities.py

now using the december 2022 data on local authority -> combined authority mapping
Fixes #465

update to fetching latest combined authority mapping data

---

scoring/static/scoring/scss/methodology.scss
scoring/static/scoring/scss/toggle-section.scss
scoring/templates/scoring/includes/main-filter-methodology.html
scoring/templates/scoring/methodology2023.html
scoring/views.py

This PR includes:
- The latest [web copy](https://docs.google.com/document/d/1wrj23W_Wa3dNVPebUlqowdpb4RQJy2DWAnCJOMpGFcw/edit)
-  The [question list for CA](https://docs.google.com/spreadsheets/d/1cc0PvkSaEngS-9Xti1lrUMftLPDJm59_Y4WL5zW6--A/edit#gid=1455862221)
Fixes: https://github.com/mysociety/caps/issues/480

[Scorecards] Combined authorities  methodology 2023

---

scoring/templates/scoring/includes/main-filter-methodology.html
scoring/templates/scoring/methodology2023.html
scoring/views.py

This PR has some errors in the copy spotted by CEUK.
Part of: https://github.com/orgs/mysociety/projects/24/views/2?pane=issue&itemId=19970395

[Scorecards] Updated web copy for Combined Authority

---

caps/templates/caps/includes/council-document.html

fix missing document title for plans with no title

---

scoring/templates/scoring/home.html
scoring/templates/scoring/includes/main-filter.html

New horizontal layout for homepage features.

Scorecards 2023 homepage features layout

---

scoring/models.py
scoring/static/scoring/scss/main.scss
scoring/static/scoring/scss/methodology.scss
scoring/static/scoring/scss/table-question-council.scss
scoring/static/scoring/scss/toggle-buttons.scss
scoring/templates/scoring/base.html
scoring/templates/scoring/home.html
scoring/templates/scoring/section.html
scoring/templates/scoring/sections.html
scoring/urls.py
scoring/views.py

Fixes: https://github.com/mysociety/caps/issues/516
https://github.com/mysociety/caps/assets/13790153/dbebc776-032e-4f24-8b3b-f6ed3964c992
https://github.com/mysociety/caps/assets/13790153/325f385d-2dae-4280-8900-d3baffcf245a
This PR also includes feedback from CEUK(13 Sept 2023):

Scorecards 2023 sections

---

caps/helpers/council_navigation.py
caps/templates/caps/council_cards/scorecard.html
caps/views.py

display action scorecards on CAPE instead of plan scorecards

---

scoring/static/scoring/scss/table-question-council.scss
scoring/templates/scoring/about.html
scoring/templates/scoring/base.html
scoring/templates/scoring/contact.html
scoring/templates/scoring/council.html
scoring/templates/scoring/home.html
scoring/templates/scoring/home_combined.html
scoring/templates/scoring/how-to-use-the-scorecards.html
scoring/templates/scoring/includes/advanced-filter.html
scoring/templates/scoring/section.html
scoring/templates/scoring/sections.html
scoring/views.py

Fixes: https://github.com/mysociety/caps/issues/577

577 Non Static Pages

---

scoring/static/scoring/scss/main.scss
scoring/templates/scoring/about.html
scoring/templates/scoring/contact.html
scoring/templates/scoring/how-to-use-the-scorecards.html

Fixes: https://github.com/mysociety/caps/issues/528
2023 copy for:
https://github.com/mysociety/caps/assets/13790153/f8ce557d-58a2-4a32-a8e0-22dab4d16224
https://github.com/mysociety/caps/assets/13790153/15d3aef1-86b0-4525-905a-d64e677a58cf

Static pages

---

scoring/models.py
scoring/templates/scoring/council.html
scoring/templates/scoring/home.html
scoring/templates/scoring/section.html
scoring/views.py

use percentages for section scores

---

scoring/templates/scoring/includes/question-content-table-cell.html
scoring/views.py

Also tiny bit or de-deduplication refactoring.

fix missing section page question criteria

---

scoring/templates/scoring/base.html
scoring/templates/scoring/home.html
scoring/views.py

[scorecards] add canonical meta tag on all pages

---

caps/templates/caps/404.html
caps/urls.py
caps/views.py
scoring/templates/scoring/404.html
scoring/urls.py
scoring/views.py

add 404 pages to CAPE and Scorecards

---

caps/management/commands/link_combined_authorities.py
caps/templates/caps/council_cards/new-council.html
proj/settings.py

New combined authority!
All the underlying datasets have been updated - this just needs to be merged, and then run an `--all` update after running the normal update.

Add york, north yorkshire ca

---

caps/templates/caps/council_cards/climate-documents.html

Also tighten up the vertical spacing, while I was in the area.

Improve wording of council documents card "Info" header

---

scoring/templates/scoring/council.html

[scorecards] Add warning about late marking to Isles of Scilly

---

caps/api/serializers.py
caps/api/views.py
caps/tests/test_api.py
caps/urls.py

Lets people get the list of council documents from the API

add a documents end point to the API

---

scoring/templates/scoring/includes/home-announcement.html

Awaiting final wording from CE UK.

[Scorecards] Updated 2023 homepage banner wording for 2025 launch
