mysociety/caps

.github/workflows/django.yml, .gitignore, README.md, Vagrantfile, caps/forms.py, caps/search_indexes.py, caps/templates/search_results.html, caps/tests/test_views.py, caps/urls.py, caps/views.py, conf/config.py-example, conf/packages, conf/post_deploy_actions.bash, conf/schema.xml, conf/solrconfig.xml, proj/settings.py, requirements.txt, script/bootstrap, script/server, script/update, templates/plandocument_text_index.txt
Adds fulltext search using [Solr 6.6](https://lucene.apache.org/solr/guide/6_6/) through [Haystack 3](https://django-haystack.readthedocs.io/en/master/)
I've added some example parameters passed to Solr for the snippets and highlighting in the text search results in `HighlightedSearchForm` in `caps/forms`. Through these parameters, we can change (I think) anything listed in 
[https://lucene.apache.org/solr/guide/6_6/highlighting.html#Highlighting-Usage](https://lucene.apache.org/solr/guide/6_6/highlighting.html#Highlighting-Usage)
Not sure about adding integration tests here - I feel a bit guilty about not adding any, but there's so little code around the search that they'd be testing the code, so much as testing that solr is present and the data is indexed. Feels like trying to write …
=> Solr fulltext search

README.md, caps/management/commands/add_text.py, caps/management/commands/import_emissions_data.py, caps/management/commands/import_plans.py, caps/management/commands/preprocess.py, script/update
This allows cached data to be used on a standard run of `script/update` (if any data has previously been loaded). A run with the flag `script/update --all` will produce a comprehensive update. It's worth noting that it's not necessary to run `script/update` every time a vagrant box is restarted - it basically just loads data, rather than updating the code or dependencies. 
Fixes #42
Fixes #36
=> Add a faster version of the slow bits of script/update

caps/context_processors.py, caps/templates/base.html, conf/config.py-example, conf/config.py.docker, proj/settings.py
`client_storage` is turned off to prevent a tracking cookie being used
=> Add google analytics

requirements.txt
This updates requests, urllib3, pillow, django and pyyaml. The latter four were flagged individually by Dependabot; the urllib3 tests failed due to the need to update requests as a dependency.
=> Bump various dependencies

caps/static/js/main.js, caps/templates/council_detail.html, caps/templates/includes/text-search-result.html
This PR solves a problem where the GA `file_download` event does not always make it easy to link back to the council the file is associated with. 
This explicitly tags up links in the council and search page with the council slug, and has a `gtag` function that catches these links and triggers a `plan_link_click` event.
=> plan_link_click analytics event created

caps/static/js/main.js, caps/templates/net_zero_local_hero.html
More tracking on the Net Zero Local Hero landing page.
Records a Google Analytics event whenever any `a[href]` on the landing page is clicked (_anywhere_ on the page, including the header and nav). Sends Google the text content of the link itself (or the image filename, if it’s a link containing only an image) and the URL that the user is about to go to.
Doesn’t track form submissions (like the postcode search form) because that’s a bit harder.
Not very pretty code, but good enough to temporarily measure activity on the landing page over COP26.
/cc @MyfanwyNixon
=> Track clicks on Net Zero Local Hero landing page

caps/api/serializers.py, caps/api/views.py, caps/management/commands/postprocess.py, caps/models.py, caps/templates/about.html, caps/tests/test_api.py, caps/urls.py
Adds link to list of promises to each council, plus an end point for
a list of all promises
This also adds in filtering for the council endpoint and moves to using the authority code to look up individual council details.
=> add council promises to the API

caps/templates/about.html, caps/templates/about_data.html, caps/urls.py, caps/views.py
Mostly so it doesn't overwhelm the about page and also so as we expand
the data we can put more information here.
=> move information about data to its own page

caps/templates/council_detail.html
Fixes a bug introduced in #163 that caused promises (“pledges”) with a scope of “other” to display on the council detail page without a heading above them, meaning they crashed into the line above.
**Before:**
**After:**
=> Make sure even “other” scope promises have a heading

docker-compose.yml, requirements.txt
Couple of very small fixups to permit a fresh clone on an Apple M1 to run and build the app container.
Note the issues with Solr, perhaps a wider discussion on what to do about upgrading this dependency is in order.
For numpy, I simply remove the version constraint then built and updated the requirements file with the version selected.
=> M1 build fixups

caps/dataframe/la.py, caps/import_utils.py, caps/management/commands/add_authority_codes.py
We now have a [repo](https://github.com/mysociety/uk_local_authority_names_and_codes) with a good source of truth for local authority information including combined authorities. 
This PR removes and updates references to older versions of this lookup, and added information that was being manually patched back into the main repo. 
This seems to setup from scratch ok, but @struan might have some other ideas about edge cases that are worth testing.
=> Changed datasources to point to new repo

caps/forms.py, caps/models.py, caps/templates/search_results.html
When following the link from the council page the name is displayed and passed back through. The comparison type is given in a dropdown.
Addresses part of https://github.com/mysociety/caps/issues/219, where the search link for similar types isn't actually usable. 
If not following the link from the council page, these options aren't visible.
=> Search form can search for similar councils

scoring/templates/scoring/home.html, scoring/templates/scoring/includes/advanced-filter.html, scoring/templates/scoring/includes/main-filter.html, scoring/views.py
Highlight which authority type we are filtering by, and also change advanced filter options appropriately.
=> use authority type on front page

scoring/templates/scoring/base.html, scoring/templates/scoring/home.html
From this:
To this:
@MyfanwyNixon I take it we’re ok with this wording?
=> Better holding page for Scorecards site

caps/management/commands/add_council_websites.py, caps/management/commands/import_plans.py
Small fix: Fixed a current error when importing from council websites.
Bigger fix:  https://github.com/mysociety/caps/issues/216 requires changing a council's name, but currently that would lead to duplicate entries. This changes the council import process to just check for uniqueness on code and country.
=> Unique council loading

proj/settings.py
Change scorecard dataset to v1 - this should be the final version.
The dataset passes automated tests, and included some additional plans identified as missing.
=> Set scorecard data to v1

scoring/static/scoring/js/main.js, scoring/static/scoring/scss/table-question-council.scss, scoring/templates/scoring/council.html
(It’s an accordion, so only one section can be open at a time. Opening a section scrolls you up/down so that it fills your viewport as you’d expect.)
=> Council page question table fixes

script/server
Each app container will run on a host with 3 cores, so set a worker per core with 2 threads to balance CPU/memory.
=> gunicorn: Set workers and threads based on our standard app server

caps/templates/council_detail.html
Fixes #65 by reusing the BEIS wording that their “subset dataset” shows emissions “within the scope of influence of local authorities”.
Also, we now only show the "data combined" wording on County and Combined Authority pages, where it makes sense. And I’ve added a bit more margin, and tighter line spacing, to the entire message, to make it easier to read.
=> Clarify that emissions data is within scope of influence

caps/management/commands/add_council_websites.py, caps/management/commands/import_plans.py
The LGA have changed the page to use a dl rather than a table, and also
removed all the twitter handles. This updates the parser to deal with
that, and also to only update the twitter handle if it's not blank.
=> update english council url scraping

scoring/templates/scoring/methodology.html
This one should have been added to #325! Oh well.
=> Remove Kent councils from Suffolk section of Scorecards Methodology

scoring/static/scoring/scss/scoring-table.scss, scoring/templates/scoring/home.html
Fixes https://github.com/mysociety/caps/issues/320
On mobile the background-color for the odd rows, where looking uneven do the height difference between columns. So a fixed that applies style to the tr element instead of the td elements was added.
=> Added individual messages for each council with no Plan.

caps/management/commands/import_emissions_data.py
I've fixed this error before for upper tiers where the calculation of the per person and per area emissions statistics were wrong, but missed the same applies for new unitary councils.
The `to_modern()` process sums together the calculated values, but we weren't then re-calculating the derived values like we are for county/combined. 
Slight tweak to one line, and then `script/manage import_emissions_data --all` needs to be run.
Before:
After:
=> Recalculate emissions for lower tier

caps/templates/caps/council_detail.html, caps/templatetags/caps_templatetags.py
The built in title filter capitalises after apostrophes which is a won't
fix issue (https://code.djangoproject.com/ticket/22323) so add our own
using string.capwords() which is better suited for plan document titles.
=> add filter for capitalising document titles

caps/static/caps/scss/backgrounds.scss, caps/static/caps/scss/ceuk-card.scss, caps/templates/council_detail.html
I moved the search bar to the top and replaced the label with a placeholder instead. I think the council page is quite busy at the moment, there are a lot of elements that draw attention, such as links and elements with colours, so I thought about economising and getting rid of the label.
I put the google form message at the bottom of the "Climate documents". Same reason as before, I wouldn't use h2 or make the message pop up that much. Give it enough visibility, so users know it is there without making it look like the most important part.
=> Changed layout "Climate Documents" card

caps/templates/caps/council_detail.html
@zarino, I found a minor bug when testing the council page on mobile.
The data for the "EMISSIONS REDUCTION PROJECTS" overflows on mobile. I checked on the live website as well.
Let me know if it fits the bill =)
=> Fixed nowrap behaviour on mobile

scoring/static/scoring/scss/scoring-table.scss
I found an issue on desktop when scrolling horizontally on the main table. 
https://user-images.githubusercontent.com/13790153/172571073-f336bed6-413b-4bba-9096-b148f977e63f.mov
https://user-images.githubusercontent.com/13790153/172571520-8b61192a-9a4a-4b49-88b7-9a882a01035c.mov
=> [Scorecards] Added  fix preventing overlapping of cells on main table

caps/static/caps/scss/variables.scss, caps/templates/caps/council_detail.html
Hi @zarino
The first commit improves the accessibility issues found on the council page, where teal, cyan, green, and other colours weren't passing the contrast test. I checked the other pages to see if I could find an issue with the changes, but I didn't find any.
The rest of the commits are not about accessibility but scannability on a council page.
Because there are many interactive elements(purple), we have a lot of colour on the page, which is a bit overwhelming and hard to scan. Therefore, I made the following changes to improve scannability:
- DECLARATIONS & PLEDGES card is now grey, so the titles have a neutral colour.
- The cards in the left sidebar are now grey as well. Most of them were purple, which was confusing cause we used purple mostly for interactive elements.
- The …
=> Improved council page accessibility (colour contrast)

scoring/static/scoring/scss/input.scss, scoring/templates/scoring/base.html
I've used the paypal button from the CEUK page as the link provided didn't seem to work and also I suspect paypal requires you to use their button.
What I can't work out is how to disable the hover effect of the background colour showing through. I've set the transition to none but no joy. Possibly @lucascumsille can fix this.
Fixes #409
=> [scorecards] update donate button in page header

caps/static/caps/js/main.js
The submit handler for the interstitial was no longer setting the never
show again property in local storage, but the download modal was so swap
these around.
=> [CAPE] fix modal submit handlers

caps/management/commands/import_plans.py, caps/search_indexes.py, script/trial_update, script/update, templates/plandocument_text_index.txt
Use the built in file extraction for document indexing which allows indexing documents other than PDF.
=> 129 improved document indexing

caps/management/commands/postprocess.py
This is not longer present so trying to drop it causes an error.
Fixes #423
=> [CAPE] don't try to drop text column when cleaning plans csv

caps/models.py, scoring/fixtures/test_homepage.json, scoring/tests/test_views.py
When the authority_type code for NI councils was updated SCORING_GROUPS
wasn't updated to reflect this so the query wasn't matching any NI
councils. Update SCORING_GROUPS, and add some tests for the homepage.
Fixes #422
=> [scorecards] fix empty list of northern ireland councils

scoring/templates/scoring/council.html, scoring/templates/scoring/includes/advanced-filter.html, scoring/templates/scoring/methodology.html
Wording for the filter "Current political control" wasn't very accurate after having elections, so it has been changed to "Political control (Jan 2022)".
Changed on the following pages:
-Home page (Advanded filtes)
-Methodology
-Council page
Fixes: #425 
Let me know if there is any feedback.
=> Changed wording for "Current political control"

scoring/static/scoring/scss/about.scss, scoring/static/scoring/scss/buttons.scss, scoring/static/scoring/scss/down-message.scss, scoring/static/scoring/scss/how-to-use.scss, scoring/static/scoring/scss/methodology.scss
Fixes #457.
@lucascumsille I’m not sure whether you can remember why you set `a { display: table }` in the first place, [twelve months ago](https://github.com/mysociety/caps/commit/a0f27cbb4e65bc16b63c0739b0dd4bab0a11cc2b#diff-83f5423dfb80034b5387e0bbbd446f0df5449cc94214ddd9ffe72cb326f94e92R24) – if you can, then maybe you can comment on whether this PR will break anything non-obvious? If not, perhaps you could check over the pages of the site, and confirm you’re happy with how it all looks now. I’ve done a quick sweep, and haven’t noticed anything looking broken.
=> [Scorecards] Anchor elements no longer display:table

caps/templates/caps/base.html
Enables us to keep the site URL out of templates, making it easier to keep absolute links up to date if we ever change URL (which we’re likely to do as part of https://github.com/mysociety/caps/issues/225).
It was tempting to use the domain from `request.META.HTTP_HOST` but this is provided by the client, not the server, so ideally shouldn’t be trusted.
Eventually, I guess, we might want `SiteUrlMixin` to pull the URL out of a server environment variable, so it could be set by a provisioning script, or whatever. But hard-coding it in `mixins.py` seemed a good first step.
Fixes #146.
=> [CAPE] Refactor site URL into context mixin

.github/workflows/mirror.yml
Buster update required update to action-git-pusher (https://github.com/mysociety/action-git-pusher/pull/2)
Increment version to new v1.1.1 tag.
=> Git mirror action update

caps/templates/caps/base.html
Using the wrong style for cookie consent in GA-4.
See: https://stackoverflow.com/questions/67078898/how-to-disable-cookies-in-ga4
This switches to the GA4 style.
=> Switch to new style cookie disable settings

caps/static/caps/scss/site-header.scss, caps/static/caps/scss/site-hero.scss, caps/templates/caps/base.html, caps/templates/caps/home.html, caps/templates/caps/includes/plans-download-and-search.html, caps/templates/caps/includes/site-header.html, caps/templates/caps/tag_list.html, caps/urls.py, caps/views.py
- Replace `/features*` URLs with `/plans*`
- Rename “Features” to “Plans” in main nav
- Break homepage plan download and search section into its own partial (plans-download-and-search.html) and include that in both the homepage and the top of the new “Plans” page.
- New `add_context_for_plans_download_and_search` function in views.py, to provide context for the plans-download-and-search.html partial.
- Remove purple hero background for new “Plans” page.
- Add `extra_content_classes` block for adding additional classes to the `site-content` element.
TODO: Handle redirects from /features* => /plans*?
TODO: Pre-warn Vixen about the change, before this goes live? /cc @MyfanwyNixon 
Fixes #416.
=> Reframe “Features” page as “Plans” page, with download and search

caps/helpers/council_navigation.py, caps/static/caps/js/main.js, caps/static/caps/scss/content-navbar.scss, caps/templates/caps/council_cards/local-polling.html, caps/templates/caps/council_cards/representatives.html, caps/views.py
This PR adds 'Your Representatives' box to council page, which links to WriteToThem.
When doing a postcode search, a session cookie will be generated with the postcode, which is then used to pre-populate the form. Form also works fine without this.
With cookie:
Without cookie:
Also some small tweaks elsewhere:
- Reduced frequency of initial survey (25% chance rather than 100% on second page view).
- Light change to description of local polling.
=> Add 'Your Representatives' box to council page

caps/management/commands/add_council_websites.py, caps/management/commands/add_text.py, caps/management/commands/fetch_and_process_promises.py, caps/management/commands/import_plans.py, caps/management/commands/preprocess.py, caps/templates/caps/includes/text-search-result.html, caps/tests/test_import.py
I've changed the google sheet to a new simpler format, given it now just powers CAPE. 
IMPORTANT: the import will not work until this has merged because I've done this. 
This also will interpret a 'True' in the `out_of_date` column to remove from the import, letting us keep track of changes in the sheet. 
Few other loose changes:
- Added retry approach to scraper, seems to get a few of the docs it was struggling with before.
- Fixed link to document from search page - which didn't work for non-pdfs.
=> Update plans import approach

scoring/templates/scoring/base.html, scoring2022/static/scoring2022/scss/background.scss, scoring2022/static/scoring2022/scss/hero.scss, scoring2022/static/scoring2022/scss/main.scss, scoring2022/templates/scoring2022/base.html, scoring2022/templates/scoring2022/home.html
Fixes: https://github.com/mysociety/caps/issues/514
This PR includes:
- Scorecard version selection to the navigation bar 2021
- New hero section styling to match 2023, so users can easily identify which version of the scorecards they are seeing.
=> Scorecards 2021 navbar and Hero section

scoring/static/scoring/scss/hero.scss, scoring/templates/scoring/base.html, scoring/templates/scoring/privacy.html, scoring/urls.py, scoring/views.py
Fixes: https://github.com/mysociety/caps/issues/503
Preview here:
https://github.com/mysociety/caps/assets/13790153/c83873bf-6d12-4bf1-a9f5-a88f3ff20746
=> Scorecards 2023 - Privacy policy page

scoring/templates/scoring/council.html, scoring/views.py
While we were checking for councils that had not been created at the time plans were scored we weren't checking for councils that had been dissolved. This fixes that.
Fixes #564
=> [scorecards] check for disolved councils on councils page

scoring/static/scoring/js/main.js, scoring/static/scoring/scss/loading-shimmer.scss, scoring/static/scoring/scss/main.scss, scoring/templates/scoring/home.html, scoring/templates/scoring/includes/advanced-filter.html, scoring/templates/scoring/includes/main-filter.html
- JavaScript for intercepting council type button presses, and loading the pages over Ajax instead, pulling out specific elements from the new page, and injecting them into the current page, so that we don’t have to mess with resetting event listeners on any parent elements.
- Update browser URL with History.pushState, and (re-)load pages over Ajax on popState event, so that browser back/forward buttons work as you’d expect.
- “loading shimmer” animation for elements being replaced by Ajax.
- Remove conditional around “Advanced filters” button – no need to hide the Advanced Filters for Combined Authorities or NI Councils.
- Save some vertical space in the viewport by removing the useless “Scorecards results” heading and moving the “Advanced filters” button into a space above the table on …
=> [Scorecards] Load council type tables over Ajax

scoring/templates/scoring/council.html, scoring/views.py
tidies up a few loose ends of places where we're not handling missing objects correctly.
=> generate 404 page instead of 500 when section or score not found

scoring/templates/scoring/home.html, scoring/templates/scoring/methodology2023.html, scoring/views.py
Applies the latest version of the Climate Action Scorecards methodology to the "upcoming" Methodology page on the Climate Plan Scorecards site.
Fixes #541.
=> Update 2023 Methodology on 2022 site

scoring/templates/scoring/includes/question-content-table-cell.html, scoring/views.py
Only display evidence bit if we've selected a council in some way as otherwise it doesn't make sense to display the evidence section.
Fixes #595
=> [scorecards] fix section page evidence link display

scoring/static/scoring/js/main.js, scoring/templates/scoring/section.html
=> [scorecards] fix the show specific council section page dropdown

scoring/views.py
Fixes: https://github.com/mysociety/caps/issues/623
Title element and property="og:title" were still using "plan" for the Climate Action Scorecards. Both elements have been updated to replace "Climate Plan Scorecards" with "Climate Action Scorecard"
=> [Scorecards] Fixed council title property

caps/management/commands/import_plans.py, caps/templates/caps/includes/document-list.html, caps/tests/test_import.py, caps/views.py
This changes the order of document display on the council page to use the created versus updated date on the assumption that more recently added documents are more relevant, as oppose to documents that might have had a small detailed updated.
It also updates the import to ignore citizens assembly reports when deleted documents not in the plans spreadsheet, plus some small improvements to the diagnostic messages to make it easier to see what's happening.
Fixes #619 
Fixes #634
=> Small fixes to plan updates and displays

scoring/static/scoring/scss/main.scss, scoring/static/scoring/scss/navbar.scss, scoring/static/scoring/scss/years.scss, scoring/templates/scoring/includes/main-filter-methodology.html, scoring/templates/scoring/methodology.html, scoring/templates/scoring/methodology/2025/_intro.html, scoring/templates/scoring/methodology/2025/_toc.html
This PR fixes row 22 and 23:
https://docs.google.com/spreadsheets/d/19W5anmr3VIgNmR9uN--SV6fC96AIwYx29WGnbJyb6Eo/edit?pli=1#gid=63266911
- Orange navigation content bar
- Updated pdf version for the methodology
=> Draft Methodology 2025 feedback

scoring/templates/scoring/methodology/2025/_details.html, scoring/templates/scoring/methodology/2025/_intro.html
Added timeline to Methodology 2025
I added a box in the scoring process. I thought without it looked a bit odd, without it, like if all milestone text was just floating around. Let me know which colour you prefer.
=> [Scorecards] Added timeline image to methodology 2025

caps/templatetags/caps_templatetags.py, scoring/templates/scoring/council.html, scoring/templates/scoring/section.html
Fixes #699. The question, as outlined there, is:
> Can the number of marks a council got on a question ever be a fraction with more than one decimal place? And if it can, do we care if it gets rounded to one decimal place?
If the answer to either of those questions is "no" then we should be good to merge this PR.
=> Avoid displaying ".0" decimals on question marks

caps/models.py, caps/templates/caps/council_cards/scorecard.html, caps/templates/caps/includes/authority_type.html, scoring/filters.py, scoring/mixins.py, scoring/models.py, scoring/templates/scoring/council-preview.html, scoring/templates/scoring/council-top-performer-overall-preview.html, scoring/templates/scoring/council.html, scoring/templates/scoring/home.html, scoring/templates/scoring/home_combined.html, scoring/templates/scoring/includes/advanced-filter.html, scoring/templates/scoring/includes/main-filter.html, scoring/templates/scoring/question.html, scoring/templates/scoring/section-preview.html, scoring/templates/scoring/section.html, scoring/views.py, scoring2022/templates/scoring2022/council.html, scoring2022/views.py
Fixes #611.
Adds an "Advanced filter" for `authority_type`, on the Single Tier scorecard.
While I was there, I also fixed a long-standing code smell, where we had been using `authority_type` to refer to both _actual_ MapIt council authority types (eg: "UTA", "DIS", "CTY") and Scorecards scoring groups (eg: "single-tier").
This makes the PR look much more complex than it actually is. Best to review each commit separately!
=> Split single tier types

scoring/static/scoring/img/bootstrap/form-select-indicator-white.svg, scoring/static/scoring/js/main.js, scoring/static/scoring/scss/_utils.scss, scoring/static/scoring/scss/awesomplete.scss, scoring/static/scoring/scss/buttons.scss, scoring/static/scoring/scss/input.scss, scoring/static/scoring/scss/navbar.scss, scoring/static/scoring/scss/scoring-table.scss, scoring/templates/scoring/base.html, scoring/templates/scoring/home.html, scoring/templates/scoring/home_combined.html, scoring/templates/scoring/includes/advanced-filter.html, scoring/templates/scoring/includes/jump-to-council.html, scoring/templates/scoring/includes/main-filter.html
Fixes: https://github.com/mysociety/caps/issues/694
Preview:
https://github.com/user-attachments/assets/76b64c96-a19a-4631-833e-ef923dd2fdac
=> Advanced filters and New homepage layout

scoring/static/scoring/scss/table-question-council.scss, scoring/templates/scoring/includes/question-content-table-cell.html
Added "Visit question" link to question cell:
This PR also fixes the horizontal scrolling/overflowing when you press "How is this marked?" on mobile.
=> Council table fixes

caps/templates/caps/icons/arrow-down.html, caps/templates/caps/icons/arrow-up.html, scoring/static/scoring/js/main.js, scoring/static/scoring/scss/table-question-council.scss, scoring/static/scoring/scss/variables.scss, scoring/templates/scoring/question.html, scoring/views.py
https://github.com/user-attachments/assets/b302ed73-6947-49eb-8954-59f9f4b07620
https://github.com/user-attachments/assets/f92d3c56-970d-416b-b967-987788db55b2
=> [Scorecards] Added year comparison question page

scoring/static/scoring/scss/open-graph-preview.scss, scoring/templates/scoring/base-most-improved.html
=> [Scorecards] Added Chevron and 'versus' to most improved graphic

scoring/templates/scoring/council.html
Fixes: https://github.com/mysociety/caps/issues/770
When adding a council to compare the columns were mismatched. With this commit if the compared council doesn't have previous year information, then the `td` for the score will spawn two columns, instead of one.
=> [Scorecards] Added fix to council page 2023
